# Generated by Django 4.2.7 on 2024-02-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('adult_count', models.PositiveSmallIntegerField()),
                ('child_count', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
