# Generated by Django 4.2.7 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_remove_booking_adult_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
