# Generated by Django 4.2.7 on 2024-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_booking_email_booking_name_booking_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
