# Generated by Django 4.2.7 on 2024-02-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_remove_booking_check_in_remove_booking_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
