# Generated by Django 4.2.7 on 2024-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount',
        ),
    ]
