# Generated by Django 4.2.7 on 2024-02-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_room_remove_booking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
