# Generated by Django 4.2.7 on 2024-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_booking_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
