# Generated by Django 4.2.7 on 2024-02-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_booking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='special_request',
            new_name='Address',
        ),
    ]
