# Generated by Django 4.2.7 on 2024-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_rename_special_request_booking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Address',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
