# Generated by Django 4.2.7 on 2024-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_remove_booking_address_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
