# Generated by Django 4.2.7 on 2024-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_booking_status_alter_booking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
