# Generated by Django 4.2.7 on 2024-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_remove_booking_status_alter_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='FAILURE', max_length=20),
        ),
    ]
