# Generated by Django 4.2.7 on 2024-02-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0015_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
