# Generated by Django 4.2.7 on 2024-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0018_alter_booking_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/'),
        ),
    ]
