# Generated by Django 4.2.7 on 2024-02-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0020_contact_remove_booking_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='availability_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_101', models.IntegerField(default=1)),
                ('room_102', models.IntegerField(default=1)),
                ('room_103', models.IntegerField(default=1)),
                ('room_104', models.IntegerField(default=1)),
                ('room_105', models.IntegerField(default=1)),
                ('room_106', models.IntegerField(default=1)),
                ('room_107', models.IntegerField(default=1)),
                ('room_108', models.IntegerField(default=1)),
                ('room_109', models.IntegerField(default=1)),
                ('room_201', models.IntegerField(default=1)),
                ('room_202', models.IntegerField(default=1)),
                ('room_203', models.IntegerField(default=1)),
                ('room_204', models.IntegerField(default=1)),
                ('room_205', models.IntegerField(default=1)),
                ('room_206', models.IntegerField(default=1)),
                ('room_207', models.IntegerField(default=1)),
                ('room_208', models.IntegerField(default=1)),
                ('room_209', models.IntegerField(default=1)),
                ('room_301', models.IntegerField(default=1)),
                ('room_302', models.IntegerField(default=1)),
                ('room_303', models.IntegerField(default=1)),
                ('room_304', models.IntegerField(default=1)),
                ('room_305', models.IntegerField(default=1)),
                ('room_306', models.IntegerField(default=1)),
                ('room_307', models.IntegerField(default=1)),
                ('room_308', models.IntegerField(default=1)),
                ('room_309', models.IntegerField(default=1)),
            ],
        ),
    ]
