# Generated by Django 4.2.7 on 2024-02-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0021_availability_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('direct_walk', 'Direct Walk'), ('website', 'Website'), ('cash', 'Cash'), ('google_pay', 'Google Pay')], max_length=20, null=True),
        ),
    ]
