# Generated by Django 4.2.7 on 2024-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='booking',
            name='select_method',
            field=models.CharField(choices=[('no_select', 'No Select'), ('direct_walk', 'Direct Walk'), ('website', 'Website')], default='no_select', max_length=20),
        ),
    ]
