# Generated by Django 4.2.7 on 2024-02-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0023_remove_booking_payment_method_booking_select_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='select_method',
            field=models.CharField(blank=True, choices=[('no_select', 'No Select'), ('direct_walk', 'Direct Walk'), ('website', 'Website')], default='no_select', max_length=20, null=True),
        ),
    ]
