# Generated by Django 4.2.7 on 2024-02-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_alter_booking_select_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('No Amount', 'No Amount'), ('cash', 'Cash'), ('google_pay', 'Google Pay')], default='NULL', max_length=20, null=True),
        ),
    ]
