# Generated by Django 4.2.7 on 2024-02-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0025_booking_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('No Amount', 'No Amount'), ('cash', 'Cash'), ('google_pay', 'Google Pay')], default='no amount', max_length=20, null=True),
        ),
    ]
