# Generated by Django 4.2.7 on 2024-02-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0026_rename_amount_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='gst_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
